// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "lv_port_indev_template.h"
void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x313041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 200);
    lv_obj_set_height(ui_Container2, 100);
    lv_obj_set_x(ui_Container2, 2);
    lv_obj_set_y(ui_Container2, -58);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_steering1 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_steering1, 80);
    lv_obj_set_height(ui_steering1, 40);
    lv_obj_set_x(ui_steering1, -50);
    lv_obj_set_y(ui_steering1, 20);
    lv_obj_set_align(ui_steering1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_steering1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_steering1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_steering1, lv_color_hex(0x2A65A9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_steering1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_steering1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_steering1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_steering1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_steering1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_steering1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_steering1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_steeringopen = lv_label_create(ui_steering1);
    lv_obj_set_width(ui_steeringopen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_steeringopen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_steeringopen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_steeringopen, "舵机开");
    lv_obj_set_style_text_font(ui_steeringopen, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_steering2 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_steering2, 80);
    lv_obj_set_height(ui_steering2, 40);
    lv_obj_set_x(ui_steering2, 50);
    lv_obj_set_y(ui_steering2, 20);
    lv_obj_set_align(ui_steering2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_steering2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_steering2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_steering2, lv_color_hex(0x2A65A9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_steering2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_steering2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_steering2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_steering2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_steering2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_steering2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_steering2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_steeringclose = lv_label_create(ui_steering2);
    lv_obj_set_width(ui_steeringclose, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_steeringclose, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_steeringclose, LV_ALIGN_CENTER);
    lv_label_set_text(ui_steeringclose, "舵机关");
    lv_obj_set_style_text_font(ui_steeringclose, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 200);
    lv_obj_set_height(ui_Container3, 100);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 54);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x0EA434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 6);
    lv_obj_set_y(ui_Label1, -86);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "舵机");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ask10s = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ask10s, 80);
    lv_obj_set_height(ui_ask10s, 40);
    lv_obj_set_x(ui_ask10s, -50);
    lv_obj_set_y(ui_ask10s, 75);
    lv_obj_set_align(ui_ask10s, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ask10s, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ask10s, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ask10s, lv_color_hex(0x2AA98E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ask10s, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ask10s, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ask10s, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ask10s, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ask10s, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ask10s, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ask10s, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ask10slable = lv_label_create(ui_ask10s);
    lv_obj_set_width(ui_ask10slable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ask10slable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ask10slable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ask10slable, "呼叫十秒");
    lv_obj_set_style_text_font(ui_ask10slable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ask5s = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ask5s, 80);
    lv_obj_set_height(ui_ask5s, 40);
    lv_obj_set_x(ui_ask5s, 50);
    lv_obj_set_y(ui_ask5s, 75);
    lv_obj_set_align(ui_ask5s, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ask5s, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ask5s, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ask5s, lv_color_hex(0x2AA98E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ask5s, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ask5s, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ask5s, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ask5s, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ask5s, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ask5s, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ask5s, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ask5slable = lv_label_create(ui_ask5s);
    lv_obj_set_width(ui_ask5slable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ask5slable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ask5slable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ask5slable, "呼叫五秒");
    lv_obj_set_style_text_font(ui_ask5slable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ask = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_ask, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ask, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ask, 7);
    lv_obj_set_y(ui_ask, 26);
    lv_obj_set_align(ui_ask, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ask, "呼叫");
    lv_obj_set_style_text_font(ui_ask, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_exchangeto1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_exchangeto1, 20);
    lv_obj_set_height(ui_exchangeto1, 40);
    lv_obj_set_x(ui_exchangeto1, 109);
    lv_obj_set_y(ui_exchangeto1, 3);
    lv_obj_set_align(ui_exchangeto1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_exchangeto1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_exchangeto1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_exchangeto1, lv_color_hex(0x08D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_exchangeto1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_exchangeto1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_exchangeto1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_exchangeto1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_exchangeto1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_steeringmag = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_steeringmag, &ui_img_act021_png);
    lv_obj_set_width(ui_steeringmag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_steeringmag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_steeringmag, -36);
    lv_obj_set_y(ui_steeringmag, -83);
    lv_obj_set_align(ui_steeringmag, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_steeringmag, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_steeringmag, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_askmag = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_askmag, &ui_img_1076440284);
    lv_obj_set_width(ui_askmag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_askmag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_askmag, -43);
    lv_obj_set_y(ui_askmag, 30);
    lv_obj_set_align(ui_askmag, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_askmag, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_askmag, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_steering1, ui_event_steering1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_steering2, ui_event_steering2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ask10s, ui_event_ask10s, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ask5s, ui_event_ask5s, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_exchangeto1, ui_event_exchangeto1, LV_EVENT_ALL, NULL);
    lv_group_add_obj(group2, ui_steering1);
    lv_group_add_obj(group2, ui_steering2);
    lv_group_add_obj(group2, ui_ask10s);
    lv_group_add_obj(group2, ui_ask5s);
    lv_group_add_obj(group2, ui_exchangeto1);

}
