// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "lv_port_indev_template.h"
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x313041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_duoji = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_duoji, 100);
    lv_obj_set_height(ui_duoji, 50);
    lv_obj_set_x(ui_duoji, -6);
    lv_obj_set_y(ui_duoji, 36);
    lv_obj_set_align(ui_duoji, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_duoji, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_duoji, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_duoji, lv_color_hex(0x08D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_duoji, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_duoji1 = lv_label_create(ui_duoji);
    lv_obj_set_width(ui_duoji1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_duoji1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_duoji1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_duoji1, "屏幕3");
    lv_obj_set_style_text_color(ui_duoji1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_duoji1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_duoji1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pingmu2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_pingmu2, 100);
    lv_obj_set_height(ui_pingmu2, 50);
    lv_obj_set_x(ui_pingmu2, -6);
    lv_obj_set_y(ui_pingmu2, -38);
    lv_obj_set_align(ui_pingmu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pingmu2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pingmu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pingmu2, lv_color_hex(0x08D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pingmu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_pingmu2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "屏幕2");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_group_add_obj(group1, ui_duoji);
    lv_group_add_obj(group1, ui_pingmu2);
    lv_obj_add_event_cb(ui_duoji, ui_event_duoji, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pingmu2, ui_event_pingmu2, LV_EVENT_ALL, NULL);

}
