// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "lv_port_indev_template.h"
void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x313041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_duojiyzuo = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_duojiyzuo, 100);
    lv_obj_set_height(ui_duojiyzuo, 50);
    lv_obj_set_x(ui_duojiyzuo, -55);
    lv_obj_set_y(ui_duojiyzuo, -45);
    lv_obj_set_align(ui_duojiyzuo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_duojiyzuo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_duojiyzuo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_duojiyzuo, lv_color_hex(0x2DD5D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_duojiyzuo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_duojizuo1 = lv_label_create(ui_duojiyzuo);
    lv_obj_set_width(ui_duojizuo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_duojizuo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_duojizuo1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_duojizuo1, "舵机左");
    lv_obj_set_style_text_font(ui_duojizuo1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_duojiyou = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_duojiyou, 100);
    lv_obj_set_height(ui_duojiyou, 50);
    lv_obj_set_x(ui_duojiyou, 52);
    lv_obj_set_y(ui_duojiyou, -45);
    lv_obj_set_align(ui_duojiyou, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_duojiyou, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_duojiyou, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_duojiyou, lv_color_hex(0x29D6DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_duojiyou, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_duojiyou1 = lv_label_create(ui_duojiyou);
    lv_obj_set_width(ui_duojiyou1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_duojiyou1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_duojiyou1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_duojiyou1, "舵机右");
    lv_obj_set_style_text_color(ui_duojiyou1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_duojiyou1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_duojiyou1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zidong = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_zidong, 100);
    lv_obj_set_height(ui_zidong, 50);
    lv_obj_set_x(ui_zidong, -55);
    lv_obj_set_y(ui_zidong, 39);
    lv_obj_set_align(ui_zidong, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zidong, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_zidong, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_zidong, lv_color_hex(0x08D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zidong, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zidong1 = lv_label_create(ui_zidong);
    lv_obj_set_width(ui_zidong1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zidong1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_zidong1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zidong1, "舵机自动");
    lv_obj_set_style_text_color(ui_zidong1, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zidong1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zidong1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pingmu1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_pingmu1, 100);
    lv_obj_set_height(ui_pingmu1, 50);
    lv_obj_set_x(ui_pingmu1, 50);
    lv_obj_set_y(ui_pingmu1, 38);
    lv_obj_set_align(ui_pingmu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pingmu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pingmu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pingmu1, lv_color_hex(0x29D6DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pingmu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pingmu11 = lv_label_create(ui_pingmu1);
    lv_obj_set_width(ui_pingmu11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pingmu11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pingmu11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pingmu11, "屏幕1");
    lv_obj_set_style_text_color(ui_pingmu11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pingmu11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pingmu11, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_duojiyzuo, ui_event_duojiyzuo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_duojiyou, ui_event_duojiyou, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zidong, ui_event_zidong, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pingmu1, ui_event_pingmu1, LV_EVENT_ALL, NULL);

    lv_group_add_obj(group3, ui_duojiyzuo);
    lv_group_add_obj(group3, ui_duojiyou);
    lv_group_add_obj(group3, ui_zidong);
    lv_group_add_obj(group3, ui_pingmu1);
}
