// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "lv_port_indev_template.h"
#include "stdio.h"
#include "PWM.h"
#include "debug.h"
#include "my_usart8.h"
///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_yedicishu1;
lv_obj_t * ui_wendu1;
lv_obj_t * ui_wendu2;
lv_obj_t * ui_wendu3;
lv_obj_t * ui_shidu1;
lv_obj_t * ui_shidu2;
lv_obj_t * ui_shidu3;
lv_obj_t * ui_xinglv1;
lv_obj_t * ui_xinglv2;
lv_obj_t * ui_xinglv3;
void ui_event_dianling1(lv_event_t * e);
lv_obj_t * ui_dianling1;
lv_obj_t * ui_dianliang2;
lv_obj_t * ui_dianliang3;
lv_obj_t * ui_yedicishu3;
lv_obj_t * ui_yedicishu2;
lv_obj_t * ui_yue;
lv_obj_t * ui_tian;
lv_obj_t * ui_time;
void ui_event_exchangeto2(lv_event_t * e);
lv_obj_t * ui_exchangeto2;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Container2;
void ui_event_steering1(lv_event_t * e);
lv_obj_t * ui_steering1;
lv_obj_t * ui_steeringopen;
void ui_event_steering2(lv_event_t * e);
lv_obj_t * ui_steering2;
lv_obj_t * ui_steeringclose;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Label1;
void ui_event_ask10s(lv_event_t * e);
lv_obj_t * ui_ask10s;
lv_obj_t * ui_ask10slable;
void ui_event_ask5s(lv_event_t * e);
lv_obj_t * ui_ask5s;
lv_obj_t * ui_ask5slable;
lv_obj_t * ui_ask;
void ui_event_exchangeto1(lv_event_t * e);
lv_obj_t * ui_exchangeto1;
lv_obj_t * ui_steeringmag;
lv_obj_t * ui_askmag;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_act[1] = {&ui_img_act021_png};
void update_value(double num);
void update_value1(double num);
void update_value2(double num);
void update_value3(double num);
extern uint8_t TTS[1024];                     //语音助手传输数据
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void update_value3(double num) {//液滴低落次数
   static int value = 0;
    value = (uint8_t)num;//这里写接受到的低落次数的数据
   if (value <= 60) {
       // 更新Arc的值
       lv_slider_set_value(ui_yedicishu1, value, LV_ANIM_ON);
       char buf[4]; // 数字转换为字符串的缓冲区
       snprintf(buf, 4, "%d", value);
       lv_label_set_text(ui_yedicishu3, buf);   // 更新Label的显示
   } else {
       value=0;

   }
}
void update_value(double num){//温度更新放置
   static int value = 0;
   value= (uint8_t)num;//这里改温度的数据
   if (value <= 100) {
       lv_arc_set_value(ui_wendu1, value);  // 更新Arc的值

       char buf[4]; // 数字转换为字符串的缓冲区
       snprintf(buf, 4, "%d", value);
       lv_label_set_text(ui_wendu3, buf);   // 更新Label的显示
   } else {
       value=0;
   }
}
void update_value1(double num) {//湿度放置
     static int value = 0;
     value= (uint8_t)num;//这湿度的数据
     if (value <= 100) {
         lv_arc_set_value(ui_shidu1, value);  // 更新Arc的值

         char buf[4]; // 数字转换为字符串的缓冲区
         snprintf(buf, 4, "%d", value);
         lv_label_set_text(ui_shidu3, buf);   // 更新Label的显示
     } else {
         value=0;
     }
 }
void update_value2(double num) {//更新事件arc和lable都在这里更新
     static int value = 0;
     value= (uint8_t)num;//这写心率的传过来的数据
     if (value <= 150) {
         lv_arc_set_value(ui_xinglv1, value);  // 更新Arc的值

         char buf[4]; // 数字转换为字符串的缓冲区
         snprintf(buf, 4, "%d", value);
         lv_label_set_text(ui_xinglv3, buf);   // 更新Label的显示
     } else {
         value=0;
     }
 }

void ui_event_exchangeto2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        switch_focus_group(group2);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_steering1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
       Servo_SetAngle(0);
    }
}
void ui_event_steering2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Servo_SetAngle(180);
    }
}
void ui_event_ask10s(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TTS[0] = TTS_ask10s;              //语音传输
        uartWriteHeartStr(TTS);
    }
}
void ui_event_ask5s(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TTS[0] = TTS_ask5s;              //语音传输
        uartWriteHeartStr(TTS);
    }
}
void ui_event_exchangeto1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        switch_focus_group(group1);
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
