// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_duoji(lv_event_t * e);
extern lv_obj_t * ui_duoji;
extern lv_obj_t * ui_duoji1;
void ui_event_pingmu2(lv_event_t * e);
extern lv_obj_t * ui_pingmu2;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container1;
//void ui_event_yedicishu1(lv_event_t * e);
extern lv_obj_t * ui_yedicishu1;
void ui_event_wendu1(lv_event_t * e);
extern lv_obj_t * ui_wendu1;
extern lv_obj_t * ui_wendu2;
extern lv_obj_t * ui_wendu3;
void ui_event_shidu1(lv_event_t * e);
extern lv_obj_t * ui_shidu1;
extern lv_obj_t * ui_shidu2;
extern lv_obj_t * ui_shidu3;
void ui_event_xinglv1(lv_event_t * e);
extern lv_obj_t * ui_xinglv1;
extern lv_obj_t * ui_xinglv2;
extern lv_obj_t * ui_xinglv3;
//void ui_event_dianling1(lv_event_t * e);
extern lv_obj_t * ui_dianling1;
extern lv_obj_t * ui_dianliang2;
extern lv_obj_t * ui_dianliang3;
extern lv_obj_t * ui_yedicishu3;
extern lv_obj_t * ui_yedicishu2;
extern lv_obj_t * ui_yue;
extern lv_obj_t * ui_tian;
extern lv_obj_t * ui_shijian;
void ui_event_pingmu111(lv_event_t * e);
extern lv_obj_t * ui_pingmu111;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_duojiyzuo(lv_event_t * e);
extern lv_obj_t * ui_duojiyzuo;
extern lv_obj_t * ui_duojizuo1;
void ui_event_duojiyou(lv_event_t * e);
extern lv_obj_t * ui_duojiyou;
extern lv_obj_t * ui_duojiyou1;
void ui_event_zidong(lv_event_t * e);
extern lv_obj_t * ui_zidong;
extern lv_obj_t * ui_zidong1;
void ui_event_pingmu1(lv_event_t * e);
extern lv_obj_t * ui_pingmu1;
extern lv_obj_t * ui_pingmu11;
extern lv_obj_t * ui____initial_actions0;


void update_value1(double num);
void update_value2(double num);
void update_value3(double num);
void update_value4(double num);
void ui_event_duojiyou(lv_event_t * e);


LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
